### ISSUE TITLE
Is it available to fine-tune the lingowhale with health screening hospital record?

### ISSUE THREAD

**Issue by loveplay1983** [DeepLangAI/LingoWhale-8B#3]
Dear experts, 
Can I fine-tune the LingoWhale with the health screening hospital records? Since I need to do it for my Ph.D. project, I am confused about the JSON format and the possibility of fine-tuning LingoWhale for the extractive summarization task instead of the question-answering charge.

**Comment by lvcc2018** [comment]
Hi ~ The LingoWhale-8B can be fine-tuned to complete the summary task. As described in the `README.md`, the data can be processed into the following JSON format.
```
{
        "id": 0,
        "conversations": [
            {
                "from": "human",
                "value": <TEXT_TO_SUMMARIZE> # Text that needs to be summarized
            },
            {
                "from": "model",
                "value": <SUMMARIZATION> # Summarization of the text
            }
        ]
}
```
